# Site settings
title: Rodrigo Figueiredo
description: Aprendizado contínuo

# Build settings
markdown: kramdown
theme: minima

# Navigation links
nav_links:
  - title: Home
    url: /
  - title: Aprendizados
    url: /aprendizados
  - title: Sobre
    url: /sobre
  - title: Contato
    url: /contato

# Social media links
social_links:
  - title: Twitter
    url: https://twitter.com/seutwitter
  - title: GitHub
    url: https://github.com/seugithub

# Footer content
footer_content: "© 2023 Rodrigo Figueiredo. Todos os direitos reservados."

# Custom variables
custom_variable: "Valor Personalizado"

